### ISSUE TITLE
Not compatible with sites that are hosted at subdirectory

### ISSUE THREAD

**Issue by kingofzeal** [mkkhedawat/clexy#1]
I host my blog within a subdirectory. As per the `_config.yml`:

> If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'

and it is set up as described. However, the theme doesn't seem to take these into consideration and assumes everything is at the root, which means all the links are broken.

You can see this at https://kingofzeal.github.io/fuzzy-spork/. The same thing also happens when I run the server locally.

**Comment by mkkhedawat** [comment]
If you are talking about links in sidebar ( for example 'articles' ) , You need to update link in themes/clexy/_config.yml. They are static ones because they are menu links

In your case it would be :
```
menu:
  home: /
  articles: /fuzzy-spork/archives
  author: /fuzzy-spork/author
```
It will be live like this : https://kingofzeal.github.io/fuzzy-spork/archives/
Make sure both page are generated. you can check in public folder after `hexo generate`

**Comment by kingofzeal** [comment]
That does work, at least locally, but I'm using your repo as a git submodule on my own - I'll probably fork it and reference the fork instead, but that seems less than ideal. 

It also looks like the root `_config.yml` contains the list of where those kinds of folders are (`archive_dir`, `category_dir`, `tag_dir`), but that may be because of a theme I was using earlier. Still, it would be nice to be able to use the properties of the root `_config.yml` if possible, then the theme is completely independant of the blog content.

**Comment by mkkhedawat** [comment]
You are correct. No need to fork, I will push patch for your sub-directory use case tomorrow.

**Comment by mkkhedawat** [comment]
@kingofzeal Check latest commit. Your issue should be solved.

**Comment by kingofzeal** [comment]
That seems to fix it, at least when deployed. Now that I see how things work (I'm generally unfamiliar with Jade), I may look at a couple other things and submit a PR, if you're open to it.

**Comment by mkkhedawat** [comment]
Sure
