### ISSUE TITLE
Inquiry about home page

### ISSUE THREAD

**Issue by ghost** [mkkhedawat/clexy#3]
Hi, I like this theme very much. But I have some questions about the display of the homepage.

1. Could you tell me how to change the icon picture, the name below the picture and the short introduction?
![image](https://user-images.githubusercontent.com/54013266/70694768-58c69600-1cfb-11ea-83b0-3e58ffd79475.png)

2. I like the black and white column,  but it seems a little bit too wide for me, so did you know how to make the left black column become more narrow?
![image](https://user-images.githubusercontent.com/54013266/70695207-29645900-1cfc-11ea-91a1-a7b338d4bb34.png)

Thanks!

**Comment by mkkhedawat** [comment]
Sorry about being late.
But if it helps, icons are under `themes > clexy > source` directory.
